export const DICT = {
  ko: {
    app_title: "CROSS",
    reset_starter: "(Reset Starter)",
    home: "홈",
    swipe: "스와이프",
    liked: "좋아요 목록",
    filter: "필터",
    edit_filter: "필터 수정",
    start_swipe: "스와이프 시작",
    open_liked: "좋아요 목록",
    open_filter: "필터",
    likes_heart: "❤️",
    likes: "좋아요",
    reset: "초기화",
    apply: "적용",
    gender: "성별",
    male: "남",
    female: "여",
    all: "ALL",
    min_age: "나이 (최소)",
    max_age: "나이 (최대)",
    like_label: "LIKE",
    no_label: "NO",
    no_likes: "아직 좋아요가 없습니다. 스와이프에서 오른쪽으로 넘겨보세요.",
    lang_kr: "한국어", lang_jp: "日本語", lang_en: "English",
    theme: "테마", system: "시스템", light: "라이트", dark: "다크"
  },
  ja: {
    app_title: "CROSS",
    reset_starter: "(リセットスターター)",
    home: "ホーム",
    swipe: "スワイプ",
    liked: "いいね一覧",
    filter: "フィルター",
    edit_filter: "フィルター編集",
    start_swipe: "スワイプ開始",
    open_liked: "いいね一覧",
    open_filter: "フィルター",
    likes_heart: "",
    likes: "いいね",
    reset: "リセット",
    apply: "適用",
    gender: "性別",
    male: "男",
    female: "女",
    all: "ALL",
    min_age: "年齢（最小）",
    max_age: "年齢（最大）",
    like_label: "LIKE",
    no_label: "NO",
    no_likes: "まだ『いいね』がありません。右へスワイプしてみてください。",
    lang_kr: "한국어", lang_jp: "日本語", lang_en: "English",
    theme: "テーマ", system: "システム", light: "ライト", dark: "ダーク"
  },
  en: {
    app_title: "CROSS",
    reset_starter: "(Reset Starter)",
    home: "Home",
    swipe: "Swipe",
    liked: "Liked",
    filter: "Filter",
    edit_filter: "Edit Filter",
    start_swipe: "Start Swipe",
    open_liked: "Liked",
    open_filter: "Filter",
    likes_heart: "",
    likes: "Likes",
    reset: "Reset",
    apply: "Apply",
    gender: "Gender",
    male: "Male",
    female: "Female",
    all: "ALL",
    min_age: "Min Age",
    max_age: "Max Age",
    like_label: "LIKE",
    no_label: "NO",
    no_likes: "No likes yet. Swipe right to like.",
    lang_kr: "한국어", lang_jp: "日本語", lang_en: "English",
    theme: "Theme", system: "System", light: "Light", dark: "Dark"
  }
};
export const t = (lang, key) => (DICT[lang] && DICT[lang][key]) || DICT.en[key] || key;
